package Subastas.UsuarioSubasta;

import ImagenSerializable.ImagenSerializable;
import RecursosCompartidos.PanelImagen;
import Subastas.DatosSubasta;
import static Subastas.DatosSubasta.estadoSubasta.CANCELADA;
import static Subastas.DatosSubasta.estadoSubasta.CERRADA;
import static Subastas.DatosSubasta.estadoSubasta.VENDIDA;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.LayoutStyle;


public class PanelResumenSubsta extends javax.swing.JPanel {

    private int ancho = 200;
    private int alto = 150;
    
    private usuarioSubastaPrincipal interfaz;
    private String identificacion;
    
    public PanelResumenSubsta(usuarioSubastaPrincipal interfaz, DatosSubasta datos) {
        initComponents();
        this.identificacion = datos.getIdentificador();   
        this.lblNombre.setText(datos.getNombre());
        this.lblDescr.setText(datos.getProducto().getDescripcion());
        String fecha = datos.getFinalCronometro().atZone(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
        this.lblFecha.setText(fecha);
        String estado = "";
        switch (datos.getEstatus()) {
            case CANCELADA:
                estado += "Cancelado";
                break;
            case CERRADA:
                estado += "Cerrado";
                break;
            case VENDIDA:
                estado += "Vendido";
                break;
        }
        this.lblEstado.setText(estado);
        this.interfaz = interfaz;
        mostrarImagen(datos.getProducto().getImagen());
        
    }
    public void mostrarImagen(ImagenSerializable imagen) {
        ImagenSerializable img = imagen;
        if (img == null) {
            try {
                URL url = getClass().getResource("/Imagen_no_disponible.png");
                Path ruta = Paths.get(url.toURI());
                try {
                    img = new ImagenSerializable(ruta);
                } catch (IOException ex) {
                    img = null;
                }
            } catch (URISyntaxException ex) {
                 
            }
        }
        BufferedImage imagenTemp = null;
        if (img == null) {}
        else{
            try {
                imagenTemp = img.conseguirImagen();
            } catch (IOException ex) {
                imagenTemp = null;
            }
        }
        this.PanelImagen.removeAll();
        PanelImagen panel = new PanelImagen(imagenTemp);
        panel.setwithei(this.ancho, this.alto);
        this.PanelImagen.add(panel, BorderLayout.CENTER);
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        PanelImagen = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDescr = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        PanelImagen.setBackground(new java.awt.Color(51, 51, 255));
        PanelImagen.setPreferredSize(new java.awt.Dimension(200, 150));
        PanelImagen.setRequestFocusEnabled(false);
        PanelImagen.setLayout(new java.awt.BorderLayout());

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        lblNombre.setToolTipText("");
        lblNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDescr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescr.setText("Descripcion");
        lblDescr.setToolTipText("");
        lblDescr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("Estado");
        lblEstado.setToolTipText("");
        lblEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha");
        lblFecha.setToolTipText("");
        lblFecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblDescr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(PanelImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        this.interfaz.getDatos().suscribirse(identificacion);
    }//GEN-LAST:event_btnEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelImagen;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDescr;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
