package Subastas.UsuarioSubasta;

import Subastas.DatosSubasta;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;

 /**
 *
 * @author andre
 */
public class SelectorSubastas extends javax.swing.JPanel {

    private usuarioSubastaPrincipal interfaz;
    private HashMap<String, PanelResumenSubsta> paneles;       
    
    
    public SelectorSubastas(usuarioSubastaPrincipal interfaz) {
        initComponents();
         
        this.Contenedor.setLayout(new BoxLayout(this.Contenedor, BoxLayout.Y_AXIS));
        this.interfaz = interfaz;
        this.paneles = new HashMap<>();
    }

    public void actualizarPanelesSeleccion(HashMap<String, DatosSubasta> mapa) {
        //for (String identificador : paneles.keySet()) { //Casos en los 
        for (String identificador : new ArrayList<> (paneles.keySet())) { //Casos en los 
            if (mapa.get(identificador) == null) {
                this.Contenedor.remove(paneles.get(identificador));
                paneles.remove(identificador); //Elimina sobrantes y ya seleccionados
                
            }
            else { //No hace falta agregarlo
                mapa.remove(identificador);
            }
        }
        int contador = 0;
        for (String identificador : mapa.keySet()) {
            PanelResumenSubsta panel = new PanelResumenSubsta(this.interfaz, mapa.get(identificador));
            panel.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            panel.setMaximumSize(panel.getPreferredSize()); 
            System.out.println("Contador: " + contador++);
            this.Contenedor.add(panel);
            paneles.put(identificador,panel);
             this.Contenedor.revalidate();
             this.Contenedor.repaint();
        }
       
    }
    
    public void revisarSiYaEstaPuesto() {
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new javax.swing.JScrollPane();
        Contenedor = new javax.swing.JPanel();

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        Scroll.setViewportView(Contenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JScrollPane Scroll;
    // End of variables declaration//GEN-END:variables
}
