package Subastas.Subastador;

import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JPanel;

 
public class InterfazSubastador extends javax.swing.JFrame {
    
    public enum NombrePanelesST {
        Conexion("Conexion"),
        DarDatos("DarDatos"),
        Subasta("Subasta");
        private final String nombre;

        private NombrePanelesST(String nombre) {
            this.nombre = nombre;
        }

        public String getNombre() {
            return nombre;
        }
        
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazSubastador.class.getName());
    private DatosSubastador subastador = null;
    private HashMap<String, JPanel> paneles;
    /**
     * Creates new form InterfazSubastador
     */
    public InterfazSubastador() {
        initComponents();
        this.setResizable(false);
        this.paneles = new HashMap<>();
        this.Pantalla.setLayout(new CardLayout());
        JPanel panel = new PanelConexionSubastador(this);
        this.Pantalla.add(panel, NombrePanelesST.Conexion.getNombre());
        this.paneles.put(NombrePanelesST.Conexion.getNombre(), panel);
        panel = new PanelDarDatosSubastador(this);
        this.Pantalla.add(panel, NombrePanelesST.DarDatos.getNombre());
        this.paneles.put(NombrePanelesST.DarDatos.getNombre(), panel);
        panel = new PanelSubasta(this);
        this.Pantalla.add(panel, NombrePanelesST.Subasta.getNombre());
        this.paneles.put(NombrePanelesST.Subasta.getNombre(), panel);
        this.setResizable(false);
    }

    public void limpiar() {
        this.mostrarPanel(NombrePanelesST.Conexion);
        ((PanelDarDatosSubastador)this.getPanelEspecifico(NombrePanelesST.DarDatos)).limpiar();
        ((PanelSubasta)this.getPanelEspecifico(NombrePanelesST.Subasta)).limpiar();
    }
    
    public void mostrarPanel(NombrePanelesST tipo) {
        CardLayout layout = (CardLayout) this.Pantalla.getLayout();
        layout.show(this.Pantalla, tipo.getNombre());
    }
    
    public JPanel getPanelEspecifico(NombrePanelesST tipo) {
        return this.paneles.get(tipo.getNombre());
    }
    
    public HashMap<String, JPanel> getPaneles() {
        return paneles;
    }

    public void setPaneles(HashMap<String, JPanel> paneles) {
        this.paneles = paneles;
    }

    public JPanel getPantalla() {
        return Pantalla;
    }

    public void setPantalla(JPanel Pantalla) {
        this.Pantalla = Pantalla;
    }

    public DatosSubastador getSubastador() {
        return subastador;
    }

    public void setSubastador(DatosSubastador subastador) {
        this.subastador = subastador;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PantallaLayout = new javax.swing.GroupLayout(Pantalla);
        Pantalla.setLayout(PantallaLayout);
        PantallaLayout.setHorizontalGroup(
            PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        PantallaLayout.setVerticalGroup(
            PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazSubastador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pantalla;
    // End of variables declaration//GEN-END:variables
}
