/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Subastas.Subastador;

/**
 *
 * @author andre
 */
public class PanelConexionSubastador extends javax.swing.JPanel {
    private InterfazSubastador interfaz;
    /**
     * Creates new form PanelConexion
     */
    public PanelConexionSubastador(InterfazSubastador interfaz) {
        initComponents();
        this.interfaz = interfaz;
    }

    public void escribirMensaje(String texto) {
        this.Consola.insert(texto+'\n', 0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConectarse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();

        btnConectarse.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnConectarse.setText("Conectarse");
        btnConectarse.addActionListener(this::btnConectarseActionPerformed);

        Consola.setEditable(false);
        Consola.setColumns(20);
        Consola.setLineWrap(true);
        Consola.setRows(5);
        Consola.setToolTipText("");
        Consola.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Consola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(btnConectarse, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnConectarse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarseActionPerformed
        btnConectarse.setEnabled(false);
        boolean caso = this.interfaz.getSubastador().conectar();
        btnConectarse.setEnabled(true);
        if (caso) {
            this.interfaz.mostrarPanel(InterfazSubastador.NombrePanelesST.DarDatos);
        }
    }//GEN-LAST:event_btnConectarseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Consola;
    private javax.swing.JButton btnConectarse;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
