/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Subastas.Subastador;

import ImagenSerializable.ImagenSerializable;
import RecursosCompartidos.PanelImagen;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author andre
 */
public class PanelSubasta extends javax.swing.JPanel {
    private final int ancho = 780;
    private final int alto = 360;
    private InterfazSubastador interfaz;
    /**
     * Creates new form PanelSubasta
     */
    public PanelSubasta(InterfazSubastador interfaz) {
        initComponents();
        this.interfaz = interfaz;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        panelImagen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBitacora = new javax.swing.JTextArea();
        lblDescripcion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblPrecioActual = new javax.swing.JLabel();

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        lblNombre.setToolTipText("");
        lblNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha");
        lblFecha.setToolTipText("");
        lblFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblEstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatus.setText("Estatus");
        lblEstatus.setToolTipText("");
        lblEstatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panelImagen.setBackground(new java.awt.Color(51, 102, 255));
        panelImagen.setLayout(new java.awt.BorderLayout());

        taBitacora.setColumns(20);
        taBitacora.setRows(5);
        jScrollPane1.setViewportView(taBitacora);

        lblDescripcion.setText("Descripcion");

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar Subasta");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblPrecioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioActual.setText("PrecioAcual");
        lblPrecioActual.setToolTipText("");
        lblPrecioActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPrecioActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void darGanador() {
         JOptionPane.showMessageDialog(this, this.interfaz.getSubastador().textoFinal());
         this.interfaz.limpiar(); 
    }
    
    public void mostrarImagen(ImagenSerializable imagen) {
        ImagenSerializable img = imagen;
        if (img == null) {
            try {
                URL url = getClass().getResource("/Imagen_no_disponible.png");
                Path ruta = Paths.get(url.toURI());
                try {
                    img = new ImagenSerializable(ruta);
                } catch (IOException ex) {
                    System.out.println("MI: " + ex.getMessage());
                    img = null;
                }
            } catch (URISyntaxException ex) {
                 
            }
        }
        BufferedImage imagenTemp = null;
        if (img == null) {}
        else{
            try {
                imagenTemp = img.conseguirImagen();
            } catch (IOException ex) {
                imagenTemp = null;
            }
        }
        this.panelImagen.removeAll();
        PanelImagen panel = new PanelImagen(imagenTemp);
        panel.setwithei(this.ancho, this.alto);
        this.panelImagen.add(panel, BorderLayout.CENTER);
    }
    
    public void limpiar() {
        this.lblNombre.setText("Nombre");
        this.lblEstatus.setText("Nombre");
        this.lblDescripcion.setText("Descripcion");
        this.lblFecha.setText("Fecha");
        this.taBitacora.setText("Nombre");
        this.lblPrecioActual.setText("PrecioActual");
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioActual;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JTextArea taBitacora;
    // End of variables declaration//GEN-END:variables

    public InterfazSubastador getInterfaz() {
        return interfaz;
    }

    public void setInterfaz(InterfazSubastador interfaz) {
        this.interfaz = interfaz;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getTaBitacora() {
        return taBitacora;
    }

    public void setTaBitacora(JTextArea jTextArea1) {
        this.taBitacora = jTextArea1;
    }

    public JLabel getLblDescripcion() {
        return lblDescripcion;
    }

    public void setLblDescripcion(JLabel lblDescripcion) {
        this.lblDescripcion = lblDescripcion;
    }

    public JLabel getLblEstatus() {
        return lblEstatus;
    }

    public void setLblEstatus(JLabel lblEstatus) {
        this.lblEstatus = lblEstatus;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JPanel getPanelImagen() {
        return panelImagen;
    }

    public void setPanelImagen(JPanel panelImagen) {
        this.panelImagen = panelImagen;
    }

    public JLabel getLblPrecioActual() {
        return lblPrecioActual;
    }

    public void setLblPrecioActual(JLabel lblPrecioActual) {
        this.lblPrecioActual = lblPrecioActual;
    }


    
}
