package Subastas.Subastador;

import ImagenSerializable.ImagenSerializable;
import RecursosCompartidos.FiltroNumeros;
import RecursosCompartidos.PanelImagen;
import Subastas.DatosSubasta;
import Subastas.Producto;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.text.AbstractDocument;
import javax.swing.text.html.HTML;

/**
 *
 * @author andre
 */
public class PanelDarDatosSubastador extends javax.swing.JPanel {
    private final int anchoImage = 200;
    private final int altoImage = 100;
    private InterfazSubastador interfaz;
    private ImagenSerializable imagen = null;
    /**
     * Creates new form PanelDarDatosSubastador
     */
    public PanelDarDatosSubastador(InterfazSubastador interfaz) {
        initComponents();
        ((AbstractDocument)this.tfValorInicial.getDocument()).setDocumentFilter(new FiltroNumeros());
        this.interfaz = interfaz;
        this.panelImagen.setLayout(new BorderLayout());
        this.limpiar();
       // mostrarImagen();
    }

    public void limpiar() {
        this.tfDescripcion.setText("");
        this.tfNombre.setText("");
        this.tfValorInicial.setText("");
        this.lblArchivo.setText("Sin imagen");
        this.lblArchivo.setForeground(Color.BLACK);
        this.lblError.setText("");
        this.lblError2.setText("");
        this.imagen = null;
        this.mostrarImagen();
    }
    
    public void mostrarImagen() {
        ImagenSerializable img = this.imagen;
        if (img == null) {
            try {
                URL url = getClass().getResource("/Imagen_no_disponible.png");
                Path ruta = Paths.get(url.toURI());
                try {
                    img = new ImagenSerializable(ruta);
                } catch (IOException ex) {
                     img = null;
                }
            } catch (URISyntaxException ex) {
                 
            }
        }
         BufferedImage imagenTemp = null;
        if (img == null) {}
        else{
            try {
                imagenTemp = img.conseguirImagen();
            } catch (IOException ex) {
                imagenTemp = null;
            }
        }
        this.panelImagen.removeAll();
        PanelImagen panel = new PanelImagen(imagenTemp);
        panel.setwithei(this.anchoImage, this.altoImage);
        this.panelImagen.add(panel, BorderLayout.CENTER);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNombre = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        btnArchibo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblArchivo = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        tfValorInicial = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        lblError2 = new javax.swing.JLabel();
        panelImagen = new javax.swing.JPanel();

        tfNombre.setText(" ");
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });

        tfDescripcion.setText(" ");

        btnArchibo.setText("Buscar Archivo");
        btnArchibo.addActionListener(this::btnArchiboActionPerformed);

        btnGuardar.setText("Crear Subasta");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lblArchivo.setText("Sin imagen");

        lbl1.setText("Nombre");

        lbl3.setText("Valor inicial");

        lbl4.setText("Descripcion");

        tfValorInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValorInicialKeyTyped(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText("jLabel1");

        lblError2.setForeground(new java.awt.Color(255, 51, 51));
        lblError2.setText("jLabel1");

        panelImagen.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblError2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnArchibo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(lblArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblError2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnArchibo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
        );

        panelImagen.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    public void generarVentanaEmergente() {
        JFileChooser selector = new JFileChooser();
        int resultado = selector.showOpenDialog(this.interfaz);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            Path archoivo = selector.getSelectedFile().toPath();
            try {
                ImagenSerializable imgTemp = new ImagenSerializable(archoivo);
                this.imagen = imgTemp;
                this.lblArchivo.setText("Se encontro Imagen en : " + archoivo.toString());
                this.lblArchivo.setForeground(Color.BLACK);
            } catch (Exception ex) {
                this.lblArchivo.setText("ERROR: " + archoivo.toString() +  " No es una imagen...");
                this.lblArchivo.setForeground(Color.red);
                this.imagen = null;
            }
        }
        this.mostrarImagen(); 
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!this.tfNombre.getText().trim().isEmpty()) {
            if (!this.tfValorInicial.getText().trim().isEmpty()) {
                ImagenSerializable img = this.imagen;
                if (this.imagen == null) {
                    Path ruta = Path.of("/Imagen_no_disponible.png");
                    try {
                        img = new ImagenSerializable(ruta);
                    } catch (IOException ex) {
                        //???
                    }
                }
                Producto producto = new Producto(Integer.parseInt(this.tfValorInicial.getText()), img, this.tfDescripcion.getText());
                DatosSubasta datos = new DatosSubasta(producto, this.tfNombre.getText());
                this.interfaz.getSubastador().iniciarSubasta(datos);
                this.interfaz.mostrarPanel(InterfazSubastador.NombrePanelesST.Subasta);
                this.limpiar();
            }
            else {
                this.lblError2.setText("ERROR esta vacio");
            }
        }
        else {
            this.lblError.setText("ERROR esta vacio");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        this.lblError.setText("");
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfValorInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorInicialKeyTyped
        this.lblError2.setText("");
    }//GEN-LAST:event_tfValorInicialKeyTyped

    private void btnArchiboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchiboActionPerformed
        generarVentanaEmergente();
    }//GEN-LAST:event_btnArchiboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchibo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblError2;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfValorInicial;
    // End of variables declaration//GEN-END:variables
}
